// Ошибки
const ERROR_INCORRECT_DATA = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_DEFAULT = 500;
const CREATE_SUCCESS = 201;
const ERROR_INCORRECT_LOGIN_OR_PASSWORD = 401;
const ERROR_DELETE_CARD = 403;
const ERROR_EXISTS_EMAIL = 409;

module.exports = {
  ERROR_INCORRECT_DATA,
  ERROR_NOT_FOUND,
  ERROR_DEFAULT,
  CREATE_SUCCESS,
  ERROR_INCORRECT_LOGIN_OR_PASSWORD,
  ERROR_DELETE_CARD,
  ERROR_EXISTS_EMAIL,
};
